name: 同步air-datepicker

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点自动执行
  workflow_dispatch:

jobs:
  mirror-sync:
    runs-on: ubuntu-latest
    steps:
    - name: 克隆上游仓库
      run: |
        git clone --bare --no-tags https://github.com/frappe/air-datepicker.git air-datepicker-bare

    - name: 配置Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: 添加下游远程仓库
      working-directory: ./air-datepicker-bare
      run: |
        git remote add downstream "https://${{ secrets.ATOMGIT_USERNAME }}:${{ secrets.ATOMGIT_TOKEN }}@atomgit.com/frappe/air-datepicker.git"

    - name: 强制推送分支
      working-directory: ./air-datepicker-bare
      run: |
        git push --force downstream --all

    - name: 强制推送标签
      working-directory: ./air-datepicker-bare
      run: |
        git fetch --tags origin  # 确保获取所有标签
        git push --force downstream --tags

    - name: 清理工作目录
      run: |
        rm -rf air-datepicker-bare